import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  contacts: defineTable({
    name: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    type: v.string(),
    company: v.optional(v.string()),
    city: v.optional(v.string()),
    country: v.optional(v.string()),
    vat: v.optional(v.string()),
    isCompany: v.boolean(),
    createdAt: v.number(),
  }),
  leads: defineTable({
    name: v.string(),
    contactName: v.optional(v.string()),
    company: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    expectedRevenue: v.number(),
    stage: v.string(),
    priority: v.number(),
    source: v.optional(v.string()),
    ownerName: v.optional(v.string()),
    notes: v.optional(v.string()),
    contactId: v.optional(v.id("contacts")),
    createdAt: v.number(),
  }),
  products: defineTable({
    name: v.string(),
    sku: v.string(),
    category: v.optional(v.string()),
    type: v.string(),
    price: v.number(),
    cost: v.number(),
    qty: v.number(),
    unit: v.string(),
    createdAt: v.number(),
  }),
  saleOrders: defineTable({
    number: v.string(),
    customerId: v.id("contacts"),
    date: v.number(),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
  }),
  saleOrderLines: defineTable({
    orderId: v.id("saleOrders"),
    description: v.string(),
    qty: v.number(),
    price: v.number(),
  }).index("by_orderId", ["orderId"]),
  purchaseOrders: defineTable({
    number: v.string(),
    vendorId: v.id("contacts"),
    date: v.number(),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
  }),
  purchaseOrderLines: defineTable({
    orderId: v.id("purchaseOrders"),
    description: v.string(),
    qty: v.number(),
    price: v.number(),
  }).index("by_orderId", ["orderId"]),
  invoices: defineTable({
    number: v.string(),
    type: v.string(),
    contactId: v.id("contacts"),
    date: v.number(),
    dueDate: v.optional(v.number()),
    status: v.string(),
    notes: v.optional(v.string()),
    createdAt: v.number(),
  }),
  invoiceLines: defineTable({
    invoiceId: v.id("invoices"),
    description: v.string(),
    qty: v.number(),
    price: v.number(),
  }).index("by_invoiceId", ["invoiceId"]),
  employees: defineTable({
    name: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    jobTitle: v.optional(v.string()),
    department: v.optional(v.string()),
    salary: v.number(),
    hireDate: v.optional(v.number()),
    status: v.string(),
  }),
  leaveRequests: defineTable({
    employeeId: v.id("employees"),
    type: v.string(),
    from: v.number(),
    to: v.number(),
    days: v.number(),
    status: v.string(),
    reason: v.optional(v.string()),
    createdAt: v.number(),
  }),
  projects: defineTable({
    name: v.string(),
    color: v.string(),
    status: v.string(),
    deadline: v.optional(v.number()),
    createdAt: v.number(),
  }),
  tasks: defineTable({
    title: v.string(),
    projectId: v.id("projects"),
    stage: v.string(),
    priority: v.number(),
    assignee: v.optional(v.string()),
    dueDate: v.optional(v.number()),
    createdAt: v.number(),
  }),
  timesheets: defineTable({
    employeeId: v.id("employees"),
    projectId: v.optional(v.id("projects")),
    date: v.number(),
    hours: v.number(),
    description: v.optional(v.string()),
    createdAt: v.number(),
  }),
  helpdeskTickets: defineTable({
    title: v.string(),
    category: v.string(),
    customerId: v.optional(v.id("contacts")),
    stage: v.string(),
    priority: v.string(),
    assignee: v.optional(v.string()),
    description: v.optional(v.string()),
    createdAt: v.number(),
  }),
  manufacturingOrders: defineTable({
    number: v.string(),
    productId: v.id("products"),
    qty: v.number(),
    status: v.string(),
    scheduledDate: v.optional(v.number()),
    assignee: v.optional(v.string()),
    createdAt: v.number(),
  }),
  subscriptions: defineTable({
    name: v.string(),
    plan: v.string(),
    amount: v.number(),
    status: v.string(),
    renewalDate: v.optional(v.number()),
    customerId: v.optional(v.id("contacts")),
    createdAt: v.number(),
  }),
  campaigns: defineTable({
    name: v.string(),
    subject: v.optional(v.string()),
    status: v.string(),
    recipients: v.number(),
    opens: v.number(),
    clicks: v.number(),
    sentAt: v.optional(v.number()),
    createdAt: v.number(),
  }),
  posOrders: defineTable({
    number: v.string(),
    total: v.number(),
    itemsCount: v.number(),
    items: v.string(),
    paymentMethod: v.string(),
    cashier: v.string(),
    createdAt: v.number(),
  }),
  notes: defineTable({
    title: v.string(),
    content: v.string(),
    pinned: v.boolean(),
    updatedAt: v.number(),
    createdAt: v.number(),
  }),
  docFiles: defineTable({
    name: v.string(),
    kind: v.string(),
    sizeKb: v.number(),
    owner: v.string(),
    folder: v.string(),
    createdAt: v.number(),
  }),
  signDocs: defineTable({
    name: v.string(),
    signer: v.string(),
    status: v.string(),
    requestedAt: v.number(),
    signedAt: v.optional(v.number()),
  }),
  messages: defineTable({
    channel: v.string(),
    author: v.string(),
    content: v.string(),
    createdAt: v.number(),
  }),
});
